services:
  postgresdb:
    image: postgres:17.0-alpine
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  user-db:
    depends_on:
      - postgresdb
    image: user-db
    restart: unless-stopped
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    command: npm start

volumes:
  db:
